# Node: 10
# Path: /infra/docker-compose.yml
# Purpose: Defines and runs the full local development environment stack, including all services and their dependencies.

services:
  # Node 11: Caddy acts as the reverse proxy and entrypoint.
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "${CADDY_HTTP_PORT}:${CADDY_HTTP_PORT}"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - api
      - console

  # Node 1: The Go backend API and gRPC server.
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ../api:/app
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
      - nats

  # The Vite/React frontend console.
  console:
    build:
      context: ../console
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ../console:/app
      - /app/node_modules # Prevent local node_modules from overwriting container's
    env_file:
      - ../.env

  # Node 16: PostgreSQL database.
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  nats:
    image: nats:2.9-alpine

volumes:
  postgres_data:
  caddy_data: