# Path: /api/.air.toml
# Purpose: Configuration for the 'air' live-reloading tool for Go.

# The root directory of the project.
root = "."
tmp_dir = "tmp"

[build]
  # Command to build the application.
  cmd = "go build -o ./tmp/main ."
  # The path to the binary to run.
  bin = "./tmp/main"
  # Extensions to watch.
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Directories to exclude from watching.
  exclude_dir = ["assets", "tmp", "vendor", "gen"]
  # Log file for the build process.
  log = "air-build.log"
  # Delay between file change detection and build.
  delay = 1000 # ms
  # Stop the running app if the build fails.
  stop_on_error = true

[misc]
  # Delete the temp binary on exit.
  clean_on_exit = true